### ISSUE TITLE
std::bindした関数を直接渡せない

### ISSUE THREAD

**Issue by kuzawa** [jonigata/squall#2]
XCode 6.1.1

```
void func(int num)
{
    printf("%d", num);
}

std::function<void ()> a = std::bind(&func, 10);
_vm.defun("func", a); // ok

auto b = std::bind(&func, 10);
_vm.defun("func", b); // but compile erro
```

**Comment by kuzawa** [comment]
```
_vm.defun("func", std::bind(&func, 10)); // error
```

これがダメなんです。

**Comment by jonigata** [comment]
bindって変なもの返すんだよね〜。callableで一意のものなら大丈夫なはずなんだけど、なんで動かないんだろうか……

**Comment by jonigata** [comment]
std::_Bindにoperator()が複数あるんじゃないかなあ……だとしたらあいまいなので対処不可能

**Comment by jonigata** [comment]
んーでも曖昧だったら確か曖昧だってエラーがでるんだよな〜
なんだろこれ

**Comment by jonigata** [comment]
あ、よく見たら曖昧だってエラー出てた
多分無理かなあ……

**Comment by kuzawa** [comment]
http://stackoverflow.com/questions/27694035/how-to-stdbind-a-standard-library-algorithm
↑同じ質問ですかね。
ただやれたとしても、bindだけのためにこんなコード入れたくないので、制限というのが良さそうです。
